name: Check PR and branch

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: |
          yarn

      - name: Run lint task
        run: |
          yarn lint

      - name: Run build task
        run: |
          yarn build
