name: Upgrade LIFF SDK

on:
  schedule:
    - cron: '0 0 1 1 0'

jobs:
  update-dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version-file: '.nvmrc'

      - name: Check and Update dependencies
        run: |
          npx -p npm-check-updates ncu -u @line/liff
          yarn

      - name: Run build task
        run: |
          yarn build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
        with:
          commit-message: 'chore: upgrade LIFF SDK'
          title: 'chore: upgrade LIFF SDK'
          body: |
            - There is a new version of LIFF SDK, merge this PR to upgrade it.

          branch: update-liff-sdk
